export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_PROFILE_REPOSITORY = 'USER_PROFILE_REPOSITORY';
export const TODO_REPOSITORY = 'USER_REPOSITORY';
export const KNOWLEDGE_REPOSITORY = 'KNOWLEDGE_REPOSITORY';
export const ARTICLE_REPOSITORY = 'ARTICLE_REPOSITORY';